### ISSUE TITLE
Table clickable maken voor vakken en projecten

### ISSUE THREAD

**Issue by EmmaVandewalle** [SELab-2/UGent-2#131]

**Comment by matt01y** [comment]
De klikbaare ruimte is veel te groot.
![image](https://github.com/SELab-2/UGent-2/assets/34476708/910db107-6f4d-4971-805f-52e5f866c989)

Mijn muis is hier nog altijd boven de "knop"

**Comment by EmmaVandewalle** [comment]
Dat is niet de table maar de kaartjes, en ik zag passeren dat hier al commits voor gebeurd zijn?
