### ISSUE TITLE
Geen errors tonen wanneer iemand op een pagina zit voor een andere role

### ISSUE THREAD

**Issue by matt01y** [SELab-2/UGent-2#151]
Wanneer er nu een pagina bezocht wordt van een role anders dan de user bezit, ziet deze errors van de loaders.

Normaal zou deze user gewoon naar `https://localhost:8080/unauthorized` herleid moeten worden.

**Comment by matt01y** [comment]
@cstefc zegt dat hij dit in elke loader apart wilt handelen. Maar zou het niet beter zijn om een wrapper te maken die werkt voor alle loaders?

**Comment by cstefc** [comment]
Dat zijn geen React elementen die loaders dus ge kunt niets van routing doen daar in. Als een gefaald request goed opgevangen wordt, zouden we geen errors mogen krijgen in de loaders en dan is da probleem normaal opgelost. Die error dat er komt is dat er `{message: 'User does not have the required teacher role'}` wordt meegegeven aan de mapProjectList dus als die TODO's voor error handling worden bekeken; zou da opgelost moeten zijn.
