### ISSUE TITLE
Unauthorized page moet i18n

### ISSUE THREAD

**Issue by ALBERICLOOS** [SELab-2/UGent-2#206]

**Comment by matt01y** [comment]
Dit is al i18n op main.
![image](https://github.com/SELab-2/UGent-2/assets/34476708/0efd5aa6-d7fc-424b-a7b1-e0a4e946037b)
![image](https://github.com/SELab-2/UGent-2/assets/34476708/08eed60e-9a92-46ed-9f5f-64ac7478d345)

**Comment by EmmaVandewalle** [comment]
Bij mij ook.
