### ISSUE TITLE
UX?!?

### ISSUE THREAD

**Issue by matt01y** [SELab-2/UGent-2#208]
We kunnen intern eens kijken, maar desnoods kan ik een derde partij die meer in dat vakgebied zit vragen om advies.

**Comment by cstefc** [comment]
Ook tekst groter

**Comment by matt01y** [comment]
Zie #300 en #301

**Comment by rubben-88** [comment]
#300 en #301 zijn nu closed

**Comment by rubben-88** [comment]
<img width="624" alt="image" src="https://github.com/SELab-2/UGent-2/assets/114695283/baedaa70-9fe4-4592-9c2b-3c1f8a0089db">

- [ ] Deze minder opvallend maken.

<img width="262" alt="image" src="https://github.com/SELab-2/UGent-2/assets/114695283/24187e31-fca6-4170-84be-79c8b05e8aa0">

- [ ] Deze download button iets anders designen. Nu lijkt het alsof deze de geselecteerde file indient, maar eigenlijk download die altijd de laatste geslaagde indiening.

<img width="1120" alt="image" src="https://github.com/SELab-2/UGent-2/assets/114695283/bfbbd028-6333-41ae-8507-362a2f39449b">

- [ ] De save button hier slechts enabelen/highlighten als er iets veranderd is.

<img width="686" alt="image" src="https://github.com/SELab-2/UGent-2/assets/114695283/5cec0016-771c-40b8-bdf3-173e7369406a">

- [ ] Beetje padding langs boven bij NewProject en NewCourse bij teacher.
