### ISSUE TITLE
shortest deadline --> nearest deadline

### ISSUE THREAD

**Issue by EmmaVandewalle** [SELab-2/UGent-2#210]

**Comment by matt01y** [comment]
![image](https://github.com/SELab-2/UGent-2/assets/34476708/9dce6730-bbeb-4d2b-b714-45d8a23268c9)
![image](https://github.com/SELab-2/UGent-2/assets/34476708/4bf1fd5e-9cde-4bd7-90a3-1b1f4349caf8)
waar staat shortest deadline?

**Comment by matt01y** [comment]
ah gevonden.
![image](https://github.com/SELab-2/UGent-2/assets/34476708/4719d021-2c00-4333-a3a8-dbf3507d2ef3)

**Comment by matt01y** [comment]
Ik denk dat persoonlijk wel dat `next deadline` beter is dan `nearest deadline`.
