### ISSUE TITLE
teacher home cards laden raar

### ISSUE THREAD

**Issue by ALBERICLOOS** [SELab-2/UGent-2#249]
![image](https://github.com/SELab-2/UGent-2/assets/109024936/0f923d74-ba74-4981-b372-08de3c94902d)

**Comment by rubben-88** [comment]
<img width="1114" alt="image" src="https://github.com/SELab-2/UGent-2/assets/114695283/5206b8ad-8e63-4d39-aa84-3cd12f810c1b">
Bij mij werkt dit wel gewoon. Waarschijnlijk heeft het zichzelf opgelost.
