### ISSUE TITLE
vreemde foute request die steeds opnieuw gebeurt.

### ISSUE THREAD

**Issue by matt01y** [SELab-2/UGent-2#256]
![image](https://github.com/SELab-2/UGent-2/assets/34476708/222310ac-c8b2-4479-b253-e08cffb59fbf)

**Comment by matt01y** [comment]
gebeurt o.a. op `/student` `/studen/projects` maar ook op gelijkaardige `/teacher` routes.

**Comment by EmmaVandewalle** [comment]
Heb ik ook al gemerkt, idee wat het zou kunnen zijn?
