### ISSUE TITLE
Indienings pagina voor submissie

### ISSUE THREAD

**Issue by matt01y** [SELab-2/UGent-2#300]
Dit is nog nodig:
- [x] save moet indienen zeggen
- [x] visuele queue bij een verkeerde indiening.
- [x] text niet rood zijn bij het file uploaden als de structuur juist is.

**Comment by rubben-88** [comment]
Wacht op pr voor de groepen van stef.

**Comment by matt01y** [comment]
@rubben-88 dit is nu gedaan begin maar.
