### ISSUE TITLE
Testomgeving

### ISSUE THREAD

**Issue by matt01y** [SELab-2/UGent-2#322]
De klant zal na de presentaties jullie applicatie zelf nog eens grondig bekijken. Stuur hiervoor tegen ten laatste 24 mei een email naar de klant + lesgever met daarin de instructies om aan te melden (url, eventuele gebruikersnaam, etc). Gelieve er voor te zorgen dat de applicatie tot minstens het einde van de examenperiode blijft werken

**Comment by matt01y** [comment]
@msathieu moeten hiervoor nog praktische dingen gebeuren?

**Comment by msathieu** [comment]
Nee
