### ISSUE TITLE
Link kopieren gaat slechts 1 maal op zelfde pagina

### ISSUE THREAD

**Issue by EmmaVandewalle** [SELab-2/UGent-2#327]
![image](https://github.com/SELab-2/UGent-2/assets/105016234/b8716fa9-4443-4830-8945-a3d3caded2d0)
Eens je gekopieerd hebt, kan je het niet nog eens doen.. Ook niet als je de pop-up verlaat en dan terug opent. Je moet eerst eens van pagina veranderd zijn (state past dus niet aan bij sluiten pop-up).

**Comment by ALBERICLOOS** [comment]
Ik denk dat dit niet uitmaakt. Ik denk dat niet veel mensen nog iets anders in hun klembord gaan hebben in die tijd, ik zou deze issue dus gewoon sluiten
