### ISSUE TITLE
Optie om constraints uit te zetten

### ISSUE THREAD

**Issue by msathieu** [SELab-2/UGent-2#359]

**Comment by rubben-88** [comment]
Is het niet de bedoeling om altijd ofwel een file of een zip te zijn?

**Comment by msathieu** [comment]
Nee, de constraints kunnen ook een lege string zjin.

**Comment by rubben-88** [comment]
En wat zou dat dan betekenen? Een project waarbij je niet kan indienen, maar gewoon de info errond kunt zien?

**Comment by msathieu** [comment]
Dat zorgt ervoor dat de backend alle indieningen accepteert
