### ISSUE TITLE
Eenvoudige bestandsstructuur: mappen en bestanden worden verkeerd geplaatst.

### ISSUE THREAD

**Issue by lbarraga** [SELab-2/UGent-2#365]
Als dit de structuur is:

![image](https://github.com/SELab-2/UGent-2/assets/63658577/88d0f255-f8ad-49f9-b429-ef2dcb530a0b)

en er wordt een map toegevoegd aan de zip, is dit het resultaat:

![image](https://github.com/SELab-2/UGent-2/assets/63658577/c7866cea-285c-4d26-84e1-bcd978389ec9)

De bedoeling is echter dat deze onder `verslag.pdf` of boven `extra` komt te staan

**Comment by rubben-88** [comment]
Goed gezien, ik zal er straks eens naar kijken, ik heb voor de moment even geen laptop bij.
